### ISSUE TITLE
network_access_authorization_rules children processing logic update required

### ISSUE THREAD

**Issue by shumphr2** [netascode/terraform-ise-nac-ise#27]
The following authorization rule appears to be compliant with the schema:

```
authorization_rules:
  - name: Nested
    state: enabled
    profiles:
      - PERMIT_vlan1
    condition:
      type: ConditionOrBlock
      is_negate: false
      children:
        - type: ConditionAndBlock
          is_negate: false
          children:
            - type: ConditionReference
              is_negate: false
              name: Wired_802.1X
            - type: ConditionReference
              is_negate: false
              name: EAP-TLS
        - type: ConditionAndBlock
          is_negate: false
          children:
            - type: ConditionReference
              is_negate: false
              name: Wireless_802.1X
            - type: ConditionReference
              is_negate: false
              name: EAP-MSCHAPv2
```

but the resulting terraform plan flattens the child ConditionAndBlock entries:

```
# module.ise.ise_network_access_authorization_rule.network_access_authorization_rule["Global Policy/Nested"] will be created
+ resource "ise_network_access_authorization_rule" "network_access_authorization_rule" {
    + children            = [
        + {
            + children       = [
                + {
                    + condition_type = "ConditionReference"
                    + id             = "ddb9eb3b-fbc1-4f87-b5ef-a2a5e99c53e7"
                    + is_negate      = false
                  },
                + {
                    + condition_type = "ConditionReference"
                    + id             = "27b8d7be-6dcc-4304-92d1-d45c4efee886"
                    + is_negate      = false
                  },
                + {
                    + condition_type = "ConditionReference"
                    + id             = "aee31dce-42a9-4ad7-825b-036a894ce34c"
                    + is_negate      = false
                  },
                + {
                    + condition_type = "ConditionReference"
                    + id             = "6cb467fc-eac8-448c-b7fa-d7899d1ee844"
                    + is_negate      = false
                  },
              ]
            + condition_type = "ConditionAndBlock"
            + is_negate      = false
          },
      ]
    + condition_is_negate = false
    + condition_type      = "ConditionOrBlock"
    + default             = false
    + id                  = (known after apply)
    + name                = "Nested"
    + policy_set_id       = (known after apply)
    + profiles            = [
        + "PERMIT_vlan1",
      ]
    + state               = "enabled"
  }
```

Nesting of a single ConditionAndBlock works fine:

```
      # module.ise.ise_network_access_authorization_rule.network_access_authorization_rule["Global Policy/Single_AND"] will be created
      + resource "ise_network_access_authorization_rule" "network_access_authorization_rule" {
          + children            = [
              + {
                  + condition_type = "ConditionReference"
                  + id             = "ddb9eb3b-fbc1-4f87-b5ef-a2a5e99c53e7"
                  + is_negate      = false
                },
              + {
                  + condition_type = "ConditionReference"
                  + id             = "27b8d7be-6dcc-4304-92d1-d45c4efee886"
                  + is_negate      = false
                },
            ]
          + condition_is_negate = false
          + condition_type      = "ConditionAndBlock"
          + default             = false
          + id                  = (known after apply)
          + name                = "Single_AND"
          + policy_set_id       = (known after apply)
          + profiles            = [
              + "PERMIT_vlan1",
            ]
          + state               = "enabled"
        }
```

A single ConditionndBlock and other ConditionReference works fine also.

```
  # module.ise.ise_network_access_authorization_rule.network_access_authorization_rule["Global Policy/Nested"] will be created
  + resource "ise_network_access_authorization_rule" "network_access_authorization_rule" {
      + children            = [
          + {
              + children       = [
                  + {
                      + condition_type = "ConditionReference"
                      + id             = "ddb9eb3b-fbc1-4f87-b5ef-a2a5e99c53e7"
                      + is_negate      = false
                    },
                  + {
                      + condition_type = "ConditionReference"
                      + id             = "27b8d7be-6dcc-4304-92d1-d45c4efee886"
                      + is_negate      = false
                    },
                ]
              + condition_type = "ConditionAndBlock"
              + is_negate      = false
            },
          + {
              + condition_type = "ConditionReference"
              + id             = "6cb467fc-eac8-448c-b7fa-d7899d1ee844"
              + is_negate      = false
            },
        ]
      + condition_is_negate = false
      + condition_type      = "ConditionOrBlock"
      + default             = false
      + id                  = (known after apply)
      + name                = "Nested"
      + policy_set_id       = "14a20667-782d-4ca6-985f-ff8f6f647286"
      + profiles            = [
          + "PERMIT_vlan1",
        ]
      + state               = "enabled"
    }
```

The issue seems to be consistent for authorization and authentication rules
